### ISSUE TITLE
lack of release notes makes upgrade path unclear

### ISSUE THREAD

**Issue by EMCP** [erikdubbelboer/node-sleep#60]
I've stumbled upon a project that called for your node package at `~1.1.1`

I now see you've got quite a few more versions beyond `1.x.x`.. it would help to know which version supported what version of nodejs.. or what features / required upgrade path to take

in the end I just blindly upgraded to `sleep@~3.0.0` and the project compiled fully with no errors

For reference , this is the project . https://github.com/kaosat-dev/adafruit-i2c-pwm-driver

I will attempt to PR my changes to that child project, but they may hesitate to accept it with no clear verification / knowledge of what's changed in 2 major releases

**Comment by erikdubbelboer** [comment]
Every version of node-sleep should support node 0.8 or higher. node-sleep uses [nan](https://github.com/nodejs/nan) as compatibility layer.

The real issue here is people using node-sleep in real code instead of only using it for simple tests. A driver like that definitely shouldn't be calling sleep. It will block the whole runtime and prevent any code from executing!

**Comment by EMCP** [comment]
CC @kaosat-dev

**Comment by kaosat-dev** [comment]
Thanks a lot for the information @erikdubbelboer  & @EMCP !
